import ModeToggle from '@/components/theme/ModeToggle'
import type { Metadata } from 'next'
import Image from 'next/image'
import React from 'react'

export const metadata: Metadata ={
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}:{
    children:React.ReactNode
}){
    return (
<html lang='en'>
    <body>
    
 <div className="grid grid-cols-2">
    <div className=""></div>
<div className="">
{
            children
        }
</div>
 </div>
    </body>
</html>
    )
}